POST http://localhost:3000/api/personas HTTP/1.1
Content-Type: application/json

{ 
    "tdocpersonas":"CC",
    "ndocpersonas":"1127875664",
    "nombres":"Luis",
    "apellidos":"Garcia",
    "direccion":"Carrera 15c #67-49 norte",
    "telefono":"3619678",
    "correo":"luisfer@example.com",
    "fkrol":"Estudiante",
    "password":"Fernando001"
}

###
GET http://localhost:3000/api/personas/ HTTP/1.1

###
GET http://localhost:3000/api/personas/6545e00d1581e1593790dd35 HTTP/1.1

###
PUT http://localhost:3000/api/personas/656f8e981c025037b4a019b6 HTTP/1.1
content-Type: application/json

{
    "tdocpersonas":"CC",
    "ndocpersonas":"1127875664",
    "nombres":"Luis",
    "apellidos":"Garcia",
    "direccion":"Carrera 15c #67-49 norte",
    "telefono":"3619678",
    "correo":"luisfer@example.com",
    "fkrol":"Estudiante",
    "password":"Fernando001"
}

###
DELETE http://localhost:3000/api/personas/656f82da718da86adcaa5dfa HTTP/1.1

