
POST http://localhost:3000/api/roles HTTP/1.1
Content-Type: application/json

{
    "idroles":"R001",
    "rol":"Coordinador"
}

###
GET http://localhost:3000/api/roles HTTP/1.1

###
GET http://localhost:3000/api/roles/6545d6f6e21759335ffa7280 HTTP/1.1

###
PUT http://localhost:3000/api/roles/6545bc2f7fa59662e9dc6117 HTTP/1.1
content-Type: application/json

{
    "idroles":"R003",
    "rol":"Estudiante"
}

###
DELETE http://localhost:3000/api/roles/6545d7685c7deadc7a744b22 HTTP/1.1
